rookie:
  port: 9000
  bossThreadSize: 1
  workThreadSize: 8
  heartBeatTime: 3000 # 超时时间，单位为毫秒
  ## redis ??
  redis:
    mode: single
    database: 0
    password: 8uhb^YJm
    timeout: 3000 # ????
    poolMinIdle: 8 #?????
    poolConnTimeout: 3000
    poolSize: 10
    single:
      address: 49.232.228.92:6666
  ## rabbitmq
  rabbitmq:
    host: 49.232.228.92
    port: 5672
    virtualHost: /
    userName: rookie
    password: 8uhb^YJm
