rookie:
  port: 9000
  bossThreadSize: 1
  workThreadSize: 8
  ## redis ??
  redis:
    mode: single
    database: 0
    password: 8uhb^YJm
    timeout: 3000 # ????
    poolMinIdle: 8 #?????
    poolConnTimeout: 3000
    poolSize: 10
    single:
      address: 49.232.228.92:6666
